### PR TITLE
Feature/wiki slug resolving v2

### PR DESCRIPTION
**Pull request by hikerpig**
I've demonstrated a quick approach here  to resolve the right reference by some fields in the `frontmatter`. Though it is still somehow intrusive, but I think you can settle with it for now, until I've found a better way to do this in @gatsby-project-kb/transformer-wiki-references.

And fix the type error by some guard clause.

### CODE REVIEW

**Comment by chuan-khuna** [comment]
image

I found a bug if it is a link to external website....it will become `/posts/ml`

and the problem with `.find` and `.filter` in `gatsby-node`. I still have it

image

**Comment by hikerpig** [comment]
I see... I will fix this later

**Comment by hikerpig** [comment]
Is there some file that you have not added to the codebase？ Or could you show me which url that you got this error, so I can fix the error without missing something.

**Comment by chuan-khuna** [comment]
> Is there some file that you have not added to the codebase？ 

no, I just re-clone my repo....All files are commited.


> Or could you show me which url that you got this error, so I can fix the error without missing something.

all url does not work. but I don't have any problem with `.filter`

my os is windows 10.

**Comment by hikerpig** [comment]
OK I can figure how the error in your screenahot occurs - when there is no result from the `.find`.

Another PR later.

**Pull request merged**
